language: cpp

dist: bionic

addons:
  apt:
    sources: &default_sources
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages: &default_packages
      - xorg-dev
      - libglu1-mesa-dev

compiler:
  - gcc

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
             -DCMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER
             -DCMAKE_CXX_FLAGS=$CMAKE_CXX_FLAGS
  - make

matrix:
  include:
    - env: CMAKE_CXX_COMPILER=g++-9 CMAKE_BUILD_TYPE=Debug
      os: linux
      dist: bionic
      addons: &gcc9
        apt:
          sources: *default_sources
          packages:
            - *default_packages
            - g++-9

    - env: CMAKE_CXX_COMPILER=g++-9 CMAKE_BUILD_TYPE=Release
      os: linux
      dist: bionic
      addons: *gcc9


